In [1]:
import numpy as np
from pcm_fmm import pcm_fmm
from mydx import mydx
mydx.init()
nbasis, ngrid, nsph = mydx.get_sizes()
csph, rsph = mydx.get_spheres(nsph)
ui = mydx.get_ui(nsph, ngrid)
p = int(nbasis**0.5)-1
print(nsph, p, ngrid)
vscales, w, grid, vgrid = pcm_fmm.init_globals(p, ngrid)
ind = np.arange(1, nsph+1, dtype=np.int32)
cluster, children, parent, cnode, rnode, snode = pcm_fmm.tree_init(csph, rsph, ind)
print(cluster, children, parent, cnode, rnode, snode)
print(ind)

3 1 6
[[1 1 2 2 3]
 [3 1 3 2 3]] [[2 0 4 0 0]
 [3 0 5 0 0]] [0 1 1 3 3] [[ 0.          0.          0.          0.          0.        ]
 [ 2.837225    4.32813423  2.16406711  0.          4.32813423]
 [-1.80568427  2.49974861 -3.74962292 -4.99949723 -2.49974861]] [12.11995181  7.56368551 10.06275979  7.56368551  7.56368551] [2 5 4]
[1 3 2]


In [2]:
coef_sph = np.random.randn(nbasis, nsph)
coef_out = pcm_fmm.pcm_matvec_grid(csph, rsph, grid, w, vgrid, ui, p, vscales, ind, \
                                   cluster, children, cnode, rnode, snode, coef_sph)

In [3]:
print(coef_out)

[[-2.75647949 -1.75648422  3.2899989 ]
 [ 1.06915271  2.40648651  1.66770676]
 [-0.80775221  0.         -0.96037205]
 [ 1.65651366 -1.71068427 -0.30718117]]


In [4]:
coef_ddpcm = mydx.ddpcm_dx(coef_sph)
mat = mydx.gen_mat_ngrid(nbasis, ngrid, nsph)
print(np.tensordot(mat, coef_sph))

[[  0.39169776  -0.08595031  -0.64930023]
 [ -1.22705571   1.58573896  -0.34912125]
 [  0.64247773   3.24332608   6.25208387]
 [ -2.90975699 -10.12510669  -1.09656773]
 [ -0.4511764  -14.33395813 -12.84704014]
 [  7.42512758   3.8851278    0.01691631]]


In [5]:
print(coef_ddpcm)

[[-2.08457493  2.80231732 -1.22776278]
 [ 3.60897398  3.3189822   1.12214705]
 [-0.46170086  0.         -0.01731091]
 [ 1.65651366 -1.71068427 -0.30718117]]
